[project]
name = "devopsapi_module"
version = "0.0.1"
dependencies = [
   "redis",
   "requests",
   "python-gitlab"
]


[build-system]

requires = [
   "setuptools",
   "wheel",
   "redis",
   "requests",
   "python-gitlab"
]
build-backend = "setuptools.build_meta"